# Generated by Django 3.1.6 on 2021-10-24 08:53

import datetime
from django.db import migrations, models
import phone_field.models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dcmfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refptid', models.IntegerField()),
                ('ptrepid', models.IntegerField(blank=True, default=None, null=True)),
                ('file', models.FileField(upload_to='static/dcmfiles/')),
            ],
        ),
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('month', models.DateField(default=datetime.date.today)),
                ('expensetype', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FeedFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ptid', models.CharField(max_length=200)),
                ('repid', models.IntegerField()),
                ('file', models.FileField(upload_to='static/files/')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('item', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('ptid', models.CharField(max_length=200)),
                ('qty', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('refdoc', models.CharField(max_length=200)),
                ('refclinic', models.CharField(max_length=50)),
                ('ptid', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('study', models.CharField(max_length=200)),
                ('studydes', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
                ('discount', models.CharField(max_length=200)),
                ('payable', models.IntegerField()),
                ('paid', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('mode', models.CharField(max_length=200)),
                ('sgst', models.IntegerField(default=0)),
                ('cgst', models.IntegerField(default=0)),
                ('igst', models.IntegerField(default=0)),
                ('invid', models.IntegerField()),
                ('prescription', models.ImageField(upload_to='static/prescription/')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('item', models.CharField(max_length=200)),
                ('detail', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('orgname', models.CharField(max_length=200)),
                ('orgtype', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('gstin', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.IntegerField()),
                ('ptid', models.CharField(max_length=200)),
                ('locate', models.CharField(max_length=200)),
                ('regby', models.CharField(max_length=200)),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(default='000000', max_length=5)),
                ('medih', models.CharField(max_length=800)),
                ('refdoctor', models.CharField(max_length=50)),
                ('docid', models.IntegerField()),
                ('reffor', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Refdoctor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docid', models.IntegerField()),
                ('locate', models.CharField(max_length=200)),
                ('incentive', models.CharField(max_length=200)),
                ('regby', models.CharField(max_length=200)),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('address_1', models.CharField(max_length=128)),
                ('address_2', models.CharField(max_length=128)),
                ('city', models.CharField(max_length=64)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(default='000000', max_length=5)),
                ('other', models.CharField(max_length=800)),
                ('clinic', models.CharField(max_length=50)),
                ('clcontact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Refpt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('refptid', models.IntegerField()),
                ('centre', models.CharField(max_length=200)),
                ('regby', models.CharField(max_length=200)),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('ptid', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=6)),
                ('upload', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('btnstatus', models.CharField(max_length=20)),
                ('study', models.CharField(max_length=1000)),
                ('remark', models.CharField(max_length=800)),
                ('status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Refstudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('ptid', models.CharField(max_length=200)),
                ('repid', models.IntegerField()),
                ('locate', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('study', models.CharField(max_length=200)),
                ('text', tinymce.models.HTMLField()),
                ('repby', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('remark', models.CharField(max_length=400)),
                ('prescription', models.ImageField(upload_to='static/prescription/')),
                ('repsdate', models.DateTimeField(blank=True, null=True)),
                ('signby', models.CharField(max_length=200)),
                ('signurl', models.CharField(max_length=400)),
                ('badge', models.CharField(max_length=400)),
                ('portal', models.CharField(max_length=50)),
                ('docemail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('maincat', models.CharField(max_length=200)),
                ('subcat', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('usertype', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('organisation', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=800)),
            ],
        ),
    ]
