# Generated by Django 3.1.6 on 2021-10-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0002_remove_dcmfile_ptrepid'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcmfile',
            name='repid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
