# Generated by Django 3.1.6 on 2021-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0003_dcmfile_repid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmfile',
            name='refptid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
