# Generated by Django 3.1.6 on 2021-10-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0004_auto_20211024_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcmfile',
            name='repid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
