# Generated by Django 3.1.6 on 2021-10-29 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0006_auto_20211028_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='cbcta',
            field=models.CharField(default='No', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='cbctb',
            field=models.CharField(default='No', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='opg',
            field=models.CharField(default='No', max_length=20),
            preserve_default=False,
        ),
    ]
