# Generated by Django 3.1.6 on 2021-10-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0007_auto_20211029_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cbcta',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='cbctb',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='users',
            name='opg',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
