# Generated by Django 3.1.6 on 2021-11-04 03:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0009_report_mailstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('aptid', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('centre', models.CharField(blank=True, max_length=50, null=True)),
                ('study', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
