# Generated by Django 3.1.6 on 2021-11-04 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0011_auto_20211104_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
