# Generated by Django 3.1.6 on 2021-11-04 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0013_sign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='sid',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
