# Generated by Django 3.1.6 on 2021-11-21 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0015_auto_20211121_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='saleamount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
