# Generated by Django 3.1.6 on 2021-12-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0016_auto_20211121_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='remark',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
