# Generated by Django 3.1.6 on 2021-12-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0017_appointment_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dcm_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='refpt',
            name='dcm_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
