# Generated by Django 3.1.6 on 2022-02-01 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0019_refpt_ref_centre'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='processby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
