# Generated by Django 3.1.6 on 2022-02-01 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0020_report_processby'),
    ]

    operations = [
        migrations.AddField(
            model_name='refdoctor',
            name='referby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
