# Generated by Django 3.1.6 on 2022-02-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0021_refdoctor_referby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='processby',
            new_name='CS_processby',
        ),
        migrations.AddField(
            model_name='report',
            name='ON_processby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
