# Generated by Django 4.0.2 on 2022-03-02 09:01

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0022_auto_20220209_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Self',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vid', models.CharField(blank=True, max_length=10, null=True)),
                ('rdate', models.DateField(default=datetime.date.today)),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(blank=True)),
                ('gender', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('contact', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
            ],
        ),
    ]
