# Generated by Django 4.0.2 on 2022-03-02 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0023_self'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self',
            name='vid',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
