# Generated by Django 4.0.2 on 2022-03-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0024_alter_self_vid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='self',
            name='gender',
        ),
    ]
