# Generated by Django 4.0.3 on 2022-04-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0025_remove_self_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dprtname', models.CharField(max_length=200)),
                ('usrtype', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='users',
            name='organisation',
        ),
        migrations.AddField(
            model_name='users',
            name='orgid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
            preserve_default=False,
        ),
    ]
