# Generated by Django 4.0.3 on 2022-04-16 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0029_remove_invoice_ptid_remove_report_ptid_invoice_orgid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='orgid',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
            preserve_default=False,
        ),
    ]
