# Generated by Django 4.0.3 on 2022-04-22 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0031_rename_ptid_refpt_pid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventory',
            old_name='ptid',
            new_name='pid',
        ),
        migrations.AddField(
            model_name='inventory',
            name='orgid',
            field=models.ForeignKey(default=26, on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
            preserve_default=False,
        ),
    ]
