# Generated by Django 4.0.3 on 2022-04-28 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0034_refpt_orgid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refpt',
            name='centre',
        ),
        migrations.RemoveField(
            model_name='refpt',
            name='dcm_status',
        ),
    ]
