# Generated by Django 4.0.3 on 2022-04-30 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0035_remove_refpt_centre_remove_refpt_dcm_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 10, 59, 11, 268208)),
        ),
    ]
