# Generated by Django 4.0.3 on 2022-04-30 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0036_organisation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('pack', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rdate', models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 32, 51, 949523))),
                ('code', models.CharField(max_length=200)),
                ('head', models.CharField(max_length=200)),
                ('pack', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 11, 32, 51, 942509)),
        ),
    ]
