# Generated by Django 4.0.3 on 2022-04-30 06:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0037_modules_pack_alter_organisation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 4, 5, 329784)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 4, 5, 336805)),
        ),
    ]
