# Generated by Django 4.0.3 on 2022-04-30 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0038_alter_organisation_date_alter_pack_rdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='applied',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 13, 37, 470301)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 4, 30, 12, 13, 37, 477283)),
        ),
    ]
