# Generated by Django 4.0.3 on 2022-05-03 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0040_dcmfile_orgid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='refpt_orgid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='refptid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 14, 8, 31, 228587)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 14, 8, 31, 235568)),
        ),
    ]
