# Generated by Django 4.0.3 on 2022-05-03 11:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0041_patient_refpt_orgid_patient_refptid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 38, 51, 744015)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 3, 16, 38, 51, 751034)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='docid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='refdoctor',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
