# Generated by Django 4.0.3 on 2022-05-22 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0047_report_price_report_pt_contact_report_pt_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reg_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 0, 57, 847594)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 0, 57, 855573)),
        ),
    ]
