# Generated by Django 4.0.3 on 2022-05-22 02:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0049_organisation_regby_email_organisation_regby_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='ctperson_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 16, 18, 608823)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 22, 8, 16, 18, 615804)),
        ),
    ]
