# Generated by Django 4.0.3 on 2022-05-24 04:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0051_report_gender_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pack',
            old_name='code',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='head',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='pack',
        ),
        migrations.AddField(
            model_name='pack',
            name='scans',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pack',
            name='validity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 9, 37, 445104)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 24, 10, 9, 37, 453089)),
        ),
    ]
