# Generated by Django 4.0.3 on 2022-05-30 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0054_subscriptions_banktxnid_subscriptions_orderid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='static/logo/'),
        ),
        migrations.AddField(
            model_name='users',
            name='sign',
            field=models.ImageField(blank=True, null=True, upload_to='static/sign/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 20, 3, 10869)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 20, 3, 18880)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 14, 20, 3, 18880)),
        ),
    ]
