# Generated by Django 4.0.3 on 2022-06-05 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0057_rename_cs_processby_report_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='dci',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 20, 24, 653520)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 20, 24, 664490)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 5, 16, 20, 24, 664490)),
        ),
    ]
