# Generated by Django 4.0.3 on 2022-06-17 09:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0061_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pid',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 15, 15, 38, 285518)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 15, 15, 38, 293474)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 15, 15, 38, 294471)),
        ),
    ]
