# Generated by Django 4.0.3 on 2022-06-17 12:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0062_remove_patient_pid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 40, 34, 606786)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 40, 34, 614796)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 17, 17, 40, 34, 614796)),
        ),
    ]
