# Generated by Django 4.0.3 on 2022-06-21 11:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0069_def_study_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Def_Study',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 58, 48, 359788)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 58, 48, 368765)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 21, 16, 58, 48, 368765)),
        ),
    ]
