# Generated by Django 4.0.3 on 2022-06-29 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0075_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='edu',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='users',
            name='spec',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 6, 0, 450326)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 6, 0, 458338)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 29, 19, 6, 0, 458338)),
        ),
    ]
