# Generated by Django 4.0.3 on 2022-07-24 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0083_topcat_status_topcat_url_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prosthetic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repid', models.IntegerField(blank=True, null=True)),
                ('tooth', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 17, 42, 36, 217133)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 17, 42, 36, 227131)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 17, 42, 36, 227131)),
        ),
    ]
