# Generated by Django 4.0.3 on 2022-07-24 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0085_prosthetic_remark_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='comment',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='status',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='tracking',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 18, 38, 19, 646259)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 18, 38, 19, 655266)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 18, 38, 19, 656261)),
        ),
    ]
