# Generated by Django 4.0.3 on 2022-07-25 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0086_prosthetic_comment_prosthetic_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='casetype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 16, 5, 34, 941601)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 16, 5, 34, 950603)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 16, 5, 34, 951607)),
        ),
    ]
