# Generated by Django 4.0.3 on 2022-07-25 11:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0087_prosthetic_casetype_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 17, 8, 46, 498445)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 17, 8, 46, 507424)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 17, 8, 46, 508421)),
        ),
        migrations.CreateModel(
            name='IOSFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repid', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='static/IOSfiles/')),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation')),
            ],
        ),
    ]
