# Generated by Django 4.0.3 on 2022-07-25 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0088_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suricalguide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repid', models.IntegerField(blank=True, null=True)),
                ('tooth', models.CharField(blank=True, max_length=200, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('method', models.CharField(blank=True, max_length=200, null=True)),
                ('material', models.CharField(blank=True, max_length=200, null=True)),
                ('casetype', models.CharField(blank=True, max_length=200, null=True)),
                ('remark', models.CharField(blank=True, max_length=800, null=True)),
                ('planning', models.FileField(upload_to='static/planning/')),
                ('status', models.CharField(blank=True, max_length=800, null=True)),
                ('tracking', models.CharField(blank=True, max_length=800, null=True)),
                ('comment', models.CharField(blank=True, max_length=800, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 18, 26, 43, 84302)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 18, 26, 43, 94243)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 18, 26, 43, 94243)),
        ),
    ]
