# Generated by Django 4.0.3 on 2022-07-26 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0089_suricalguide_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='datatype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 21, 8, 119466)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 21, 8, 129437)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 21, 8, 129437)),
        ),
    ]
