# Generated by Django 4.0.3 on 2022-07-26 09:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0090_suricalguide_datatype_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='shipby',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 29, 23, 455640)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 29, 23, 465613)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 26, 15, 29, 23, 466611)),
        ),
    ]
