# Generated by Django 4.0.4 on 2022-08-05 12:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0094_comments_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 18, 26, 14, 332804)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 18, 26, 14, 348429)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 18, 26, 14, 348429)),
        ),
        migrations.CreateModel(
            name='OtherImageFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('repid', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='static/OtherImageFile/')),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation')),
            ],
        ),
    ]
