# Generated by Django 4.0.4 on 2022-08-12 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0096_imageanalysis_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='comment',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 15, 21, 23, 716332)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 15, 21, 23, 736527)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 12, 15, 21, 23, 736527)),
        ),
    ]
