# Generated by Django 4.0.4 on 2022-08-19 13:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0105_rename_casetype_suricalguide_data_type1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='planning_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 18, 58, 7, 297038)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 18, 58, 7, 312670)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 19, 18, 58, 7, 312670)),
        ),
    ]
