# Generated by Django 4.0.4 on 2022-08-27 06:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0109_report_reviewed_by_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 12, 29, 2, 628955)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 12, 29, 2, 646958)),
        ),
        migrations.AlterField(
            model_name='report',
            name='ref_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 12, 29, 2, 646958)),
        ),
    ]
