# Generated by Django 4.0.4 on 2022-09-01 13:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0110_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosfile',
            name='size',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 18, 31, 25, 106079)),
        ),
        migrations.AlterField(
            model_name='otherimagefile',
            name='file',
            field=models.FileField(upload_to='static/OtherFile/'),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 18, 31, 25, 126031)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 1, 18, 31, 25, 126031)),
        ),
    ]
