# Generated by Django 4.0.4 on 2022-09-03 07:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0112_dcmfile_size_otherimagefile_size_alter_iosfile_size_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report',
            new_name='ServiceOrder',
        ),
        migrations.AddField(
            model_name='dcmfile',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcmfile',
            name='serviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dcmfile',
            name='sodrid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedfile',
            name='serviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedfile',
            name='sodrid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='repby',
            field=models.CharField(default=12, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='signby',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='text',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iosfile',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iosfile',
            name='serviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iosfile',
            name='sodrid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dent.topcat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otherimagefile',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherimagefile',
            name='serviceid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='otherimagefile',
            name='sodrid',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='dent.topcat'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='feedfile',
            name='repid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 13, 8, 49, 413598)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 13, 8, 49, 445308)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 13, 8, 49, 445308)),
        ),
    ]
