# Generated by Django 4.0.4 on 2022-09-03 13:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0115_imageanalysis_studyinstanceuid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='iosfile',
            name='serviceid',
        ),
        migrations.AlterField(
            model_name='iosfile',
            name='sodrid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 18, 36, 29, 336198)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 18, 36, 29, 352270)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 18, 36, 29, 352270)),
        ),
    ]
