# Generated by Django 4.0.4 on 2022-09-03 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0116_remove_iosfile_serviceid_alter_iosfile_sodrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosfile',
            name='topid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 21, 28, 19, 506802)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 21, 28, 19, 531858)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 21, 28, 19, 531858)),
        ),
    ]
