# Generated by Django 4.0.4 on 2022-09-03 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0117_iosfile_topid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageanalysis',
            name='status',
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='upload',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 47, 39, 152331)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 47, 39, 165332)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 47, 39, 165332)),
        ),
    ]
