# Generated by Django 4.0.4 on 2022-09-03 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0118_remove_imageanalysis_status_imageanalysis_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='status',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 48, 50, 238035)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 48, 50, 253664)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 3, 23, 48, 50, 253664)),
        ),
    ]
