# Generated by Django 4.0.4 on 2022-09-04 07:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0121_imageanalysis_parentpatient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='orgid',
            field=models.ForeignKey(default=38, on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 12, 39, 59, 627085)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 12, 39, 59, 642716)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 12, 39, 59, 642716)),
        ),
    ]
