# Generated by Django 4.0.4 on 2022-09-06 05:57

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0125_comments_orgid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycalservices',
            name='ParentPatient',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='ParentStudy',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='StudyInstanceUID',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='order_id',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='orgid',
            field=models.ForeignKey(default=23, on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='pid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='repby',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='signby',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='text',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='upload',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 25, 49, 639764)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 25, 49, 653765)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 25, 49, 653765)),
        ),
    ]
