# Generated by Django 4.0.4 on 2022-09-06 06:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0130_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='ParentPatient',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='ParentStudy',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='StudyInstanceUID',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='repby',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='signby',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='status',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='text',
        ),
        migrations.RemoveField(
            model_name='radiologycalservices',
            name='upload',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 34, 21, 987997)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 34, 22, 3628)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 6, 11, 34, 22, 3628)),
        ),
    ]
