# Generated by Django 4.0.4 on 2022-09-08 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0133_otherimagefile_topid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycalservices',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 16, 8, 19, 59282)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 16, 8, 19, 83741)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 8, 16, 8, 19, 88642)),
        ),
    ]
