# Generated by Django 4.0.4 on 2022-09-10 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0137_radiologycalservices_badge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycalservices',
            name='portal',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='signurl',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 50, 52, 859723)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 50, 52, 875351)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 50, 52, 875351)),
        ),
    ]
