# Generated by Django 4.0.4 on 2022-09-10 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0140_radiologycalservices_name_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='patient_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 17, 18, 56, 540636)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 17, 18, 56, 556587)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 17, 18, 56, 557587)),
        ),
    ]
