# Generated by Django 4.0.4 on 2022-09-11 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0141_serviceorder_patient_id_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcat',
            name='admin_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 27, 9, 875411)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 27, 9, 899893)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 15, 27, 9, 899893)),
        ),
    ]
