# Generated by Django 4.0.4 on 2022-09-11 12:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0142_topcat_admin_url_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycalservices',
            name='CS_processby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='ON_processby',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 18, 20, 58, 806121)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 18, 20, 58, 818161)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 11, 18, 20, 58, 818161)),
        ),
    ]
