# Generated by Django 4.0.4 on 2022-09-14 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0146_radiologycalservices_sodrid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologycalservices',
            name='refer_by',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='study',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 16, 34, 467742)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 16, 34, 483373)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 15, 16, 34, 483373)),
        ),
    ]
