# Generated by Django 4.0.4 on 2022-09-16 13:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0150_alter_comments_date_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageanalysis',
            old_name='order_id',
            new_name='item_id',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 49, 49, 581157)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 49, 49, 603567)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 49, 49, 603567)),
        ),
    ]
