# Generated by Django 4.0.4 on 2022-09-16 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0151_rename_order_id_imageanalysis_item_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='service_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 54, 33, 971116)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 54, 34, 4829)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 18, 54, 34, 4829)),
        ),
    ]
