# Generated by Django 4.0.4 on 2022-09-16 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0152_imageanalysis_service_name_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='sodrid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 19, 30, 5, 33053)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 19, 30, 5, 62665)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 16, 19, 30, 5, 62665)),
        ),
    ]
