# Generated by Django 4.0.4 on 2022-09-17 08:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0153_imageanalysis_sodrid_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='badge',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 13, 54, 7, 986293)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 13, 54, 8, 6245)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 17, 13, 54, 8, 6245)),
        ),
    ]
