# Generated by Django 4.0.4 on 2022-09-18 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0160_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implantplanning',
            name='ParentPatient',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='ParentStudy',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='StudyInstanceUID',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='badge',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='date',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='file',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='item_id',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='name',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='orgid',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='repby',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='repsdate',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='service_name',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='signby',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='size',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='sodrid',
        ),
        migrations.RemoveField(
            model_name='implantplanning',
            name='status',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 16, 40, 966814)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 16, 40, 997268)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 12, 16, 41, 1791)),
        ),
    ]
