# Generated by Django 4.0.4 on 2022-09-18 12:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0166_servicelog_service_name_servicelog_sodrid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='implantplanning',
            name='upload',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 16, 12, 294669)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 16, 12, 325932)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 16, 12, 325932)),
        ),
    ]
