# Generated by Django 4.0.4 on 2022-09-18 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0167_implantplanning_upload_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageanalysis',
            name='mailstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='shipped_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='imageanalysis',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='implantplanning',
            name='mailstatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='implantplanning',
            name='shipped_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='implantplanning',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='shipped_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='radiologycalservices',
            name='tracking_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 30, 53, 28652)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 30, 53, 44280)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 18, 18, 30, 53, 44280)),
        ),
    ]
