# Generated by Django 4.0.4 on 2022-09-19 11:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0169_servicelog_patient_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='file',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 17, 5, 55, 167023)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 17, 5, 55, 194410)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 17, 5, 55, 194410)),
        ),
    ]
