# Generated by Django 4.0.4 on 2022-09-19 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0175_servicelog_line_item_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicelog',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 19, 44, 49, 879525)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 19, 44, 49, 910778)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 19, 44, 49, 910778)),
        ),
    ]
