# Generated by Django 4.0.4 on 2022-09-19 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0177_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='implantplanning',
            name='item_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 20, 8, 42, 193082)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 20, 8, 42, 208724)),
        ),
        migrations.AlterField(
            model_name='radiologycalservices',
            name='item_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 19, 20, 8, 42, 208724)),
        ),
    ]
