# Generated by Django 4.0.4 on 2022-09-20 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0179_suricalguide_parentpatient_suricalguide_parentstudy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suricalguide',
            name='size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 16, 31, 2, 713016)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 16, 31, 2, 728646)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 20, 16, 31, 2, 728646)),
        ),
    ]
