# Generated by Django 4.0.4 on 2022-09-27 14:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0184_imageanalysis_parent_orgid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='parent_orgid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='iosfile',
            name='parent_orgid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='otherimagefile',
            name='parent_orgid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='refpt',
            name='parent_orgid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 19, 53, 15, 146689)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 19, 53, 15, 206672)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 27, 19, 53, 15, 206672)),
        ),
    ]
