# Generated by Django 4.1 on 2022-10-08 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0192_suricalguide_guidedownload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='feedFileStatus',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 1, 44, 480100)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 1, 44, 513975)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 1, 44, 513975)),
        ),
    ]
