# Generated by Django 4.1 on 2022-10-08 14:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0193_suricalguide_feedfilestatus_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='feedFileComment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 6, 13, 519750)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 6, 13, 558938)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 6, 13, 559931)),
        ),
    ]
