# Generated by Django 4.1 on 2022-10-08 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0194_suricalguide_feedfilecomment_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedfile',
            name='fileName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 51, 17, 163294)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 51, 17, 199199)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 8, 20, 51, 17, 199199)),
        ),
    ]
