# Generated by Django 4.1 on 2022-10-09 13:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0196_iosfile_filename_suricalguide_iosfilecomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 19, 0, 5, 361063)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 19, 0, 5, 479827)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 9, 19, 0, 5, 482755)),
        ),
        migrations.CreateModel(
            name='DesignFile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=200)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('repid', models.IntegerField(blank=True, null=True)),
                ('serviceid', models.IntegerField(blank=True, null=True)),
                ('sodrid', models.IntegerField(blank=True, null=True)),
                ('file', models.FileField(upload_to='static/design/')),
                ('size', models.IntegerField(blank=True, null=True)),
                ('fileName', models.CharField(blank=True, max_length=150, null=True)),
                ('upload', models.CharField(blank=True, max_length=100, null=True)),
                ('fileStatus', models.CharField(blank=True, max_length=100, null=True)),
                ('fileComment', models.CharField(blank=True, max_length=100, null=True)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation')),
            ],
        ),
    ]
