# Generated by Django 4.1 on 2022-10-09 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0199_remove_suricalguide_tracking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricalguide',
            name='orderDeliverComment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suricalguide',
            name='orderDeliverConfirmationC',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suricalguide',
            name='orderDeliverConfirmationL',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='suricalguide',
            name='orderDeliverDate',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 27, 5, 712314)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 27, 5, 772261)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 10, 0, 27, 5, 772261)),
        ),
    ]
