# Generated by Django 4.0.4 on 2022-10-16 09:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0202_prosthetic_price_serviceorder_banktxnid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 14, 42, 34, 827688)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 14, 42, 34, 902898)),
        ),
        migrations.AlterField(
            model_name='prosthetic',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 16, 14, 42, 34, 902898)),
        ),
    ]
