# Generated by Django 4.0.4 on 2022-10-20 14:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0212_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('parent_orgid', models.CharField(blank=True, max_length=200, null=True)),
                ('sendTo', models.IntegerField(blank=True, null=True)),
                ('repid', models.IntegerField(blank=True, null=True)),
                ('serviceOrderId', models.CharField(blank=True, max_length=100, null=True)),
                ('lineItemId', models.CharField(blank=True, max_length=100, null=True)),
                ('service', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('usertype', models.CharField(max_length=200)),
                ('event', models.CharField(blank=True, max_length=100, null=True)),
                ('details', models.CharField(blank=True, max_length=200, null=True)),
                ('hyperLink', models.CharField(blank=True, max_length=100, null=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 20, 12, 24, 339902)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 20, 12, 24, 381906)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 20, 20, 12, 24, 381906)),
        ),
        migrations.DeleteModel(
            name='Notifications',
        ),
        migrations.AddField(
            model_name='notification',
            name='orgid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation'),
        ),
    ]
