# Generated by Django 4.0.4 on 2022-10-28 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0216_iosfile_download_iosfile_re_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='accountNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organisation',
            name='bankName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='cin',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='customFile',
            field=models.ImageField(blank=True, null=True, upload_to='static/cancelledCheque/'),
        ),
        migrations.AddField(
            model_name='organisation',
            name='ifscCode',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='pan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='organisation',
            name='regNo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 19, 31, 28, 315927)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 19, 31, 28, 406007)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 28, 19, 31, 28, 406249)),
        ),
    ]
