# Generated by Django 4.0.4 on 2022-10-29 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0217_organisation_accountnumber_organisation_bankname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='customFile',
            field=models.ImageField(blank=True, upload_to='static/cancelledCheque/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 5, 38, 208181)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 5, 38, 298194)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 5, 38, 298255)),
        ),
    ]
