# Generated by Django 4.0.4 on 2022-10-29 06:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0218_alter_organisation_customfile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='customFile',
            field=models.ImageField(null=True, upload_to='static/cancelledCheque/'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 16, 41, 812316)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 16, 41, 860068)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 29, 12, 16, 41, 860068)),
        ),
    ]
