# Generated by Django 4.0.4 on 2022-10-31 13:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0219_alter_organisation_customfile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otherimagefile',
            name='sodrid',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 18, 52, 24, 851996)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 18, 52, 24, 926401)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 31, 18, 52, 24, 926401)),
        ),
    ]
