# Generated by Django 4.0.4 on 2022-11-02 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0222_prosthetic_reforgid_suricalguide_reforgid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 17, 8, 16, 776046)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 17, 8, 16, 834841)),
        ),
        migrations.AlterField(
            model_name='prosthetic',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 17, 8, 16, 834841)),
        ),
        migrations.AlterField(
            model_name='suricalguide',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
