# Generated by Django 4.0.4 on 2022-11-02 13:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0223_alter_organisation_date_alter_pack_rdate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 19, 16, 31, 349723)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 19, 16, 31, 412237)),
        ),
        migrations.AlterField(
            model_name='prosthetic',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 19, 16, 31, 412237)),
        ),
        migrations.AlterField(
            model_name='suricalguide',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
