# Generated by Django 4.0.4 on 2022-11-03 11:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0226_suricalguide_preferreddata_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceorder',
            name='preferredData',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 17, 10, 51, 483777)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 17, 10, 51, 546296)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 3, 17, 10, 51, 546296)),
        ),
    ]
