# Generated by Django 4.0.4 on 2022-11-04 14:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0228_prosthetic_cancellationdatetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='orderPickup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='orderPickupTime',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 20, 0, 8, 704684)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 20, 0, 8, 753531)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 4, 20, 0, 8, 754534)),
        ),
    ]
