# Generated by Django 4.0.4 on 2022-11-09 14:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0230_prosthetic_availableforcollection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='fabricationComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='prevStatus',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 19, 46, 32, 229751)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 19, 46, 32, 279522)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 9, 19, 46, 32, 279522)),
        ),
    ]
