# Generated by Django 4.0.4 on 2022-11-21 14:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0236_prosthetic_application_prosthetic_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 30, 44, 470552)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 30, 44, 548697)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 21, 19, 30, 44, 548697)),
        ),
        migrations.CreateModel(
            name='Requirements',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topcat', models.CharField(blank=True, max_length=100, null=True)),
                ('findingsRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('extraFindingsRequired', models.CharField(blank=True, max_length=100, null=True)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation')),
            ],
        ),
    ]
