# Generated by Django 4.0.4 on 2022-11-22 13:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0238_radiologycalservices_finding_equires_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radiologycalservices',
            old_name='finding_equires',
            new_name='finding_requires',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 18, 46, 26, 270089)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 18, 46, 26, 313113)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 18, 46, 26, 314112)),
        ),
    ]
