# Generated by Django 4.0.4 on 2022-11-26 10:11

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0242_remove_addonlabservices_materialid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prosthetic',
            old_name='materialId',
            new_name='itemId',
        ),
        migrations.AddField(
            model_name='addonlabservices',
            name='itemId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dent.labitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 41, 34, 256016)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 41, 34, 330194)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 41, 34, 330194)),
        ),
    ]
