# Generated by Django 4.0.4 on 2022-11-26 10:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0243_rename_materialid_prosthetic_itemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonlabservices',
            name='descriptions',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='addonlabservices',
            name='unit',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 48, 40, 922561)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 48, 40, 984902)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 15, 48, 40, 984902)),
        ),
    ]
