# Generated by Django 4.0.4 on 2022-11-29 14:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0244_addonlabservices_descriptions_addonlabservices_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='addOnService',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='addOnprice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='addOnunit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 20, 10, 46, 558312)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 20, 10, 46, 637832)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 20, 10, 46, 637832)),
        ),
    ]
