# Generated by Django 4.0.4 on 2022-11-29 17:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0245_prosthetic_addonservice_prosthetic_addonprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addonlabservices',
            name='itemId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 22, 55, 22, 489865)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 22, 55, 22, 541864)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 22, 55, 22, 542864)),
        ),
    ]
