# Generated by Django 4.0.4 on 2022-11-29 17:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0246_alter_addonlabservices_itemid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='addonlabservices',
            name='repid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 23, 19, 20, 819514)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 23, 19, 20, 907516)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 29, 23, 19, 20, 908522)),
        ),
        migrations.CreateModel(
            name='ExtraLabItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('itemId', models.IntegerField()),
                ('lineItemId', models.IntegerField()),
                ('addOnService', models.CharField(blank=True, max_length=100, null=True)),
                ('unitPrice', models.IntegerField()),
                ('addOnprice', models.IntegerField(blank=True, null=True)),
                ('addOnunit', models.IntegerField(blank=True, null=True)),
                ('orgid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.organisation')),
            ],
        ),
    ]
