# Generated by Django 4.0.4 on 2022-12-05 14:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0248_remove_addonlabservices_repid_extralabitem_repid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosthetic',
            name='addOnService',
        ),
        migrations.RemoveField(
            model_name='prosthetic',
            name='addOnprice',
        ),
        migrations.RemoveField(
            model_name='prosthetic',
            name='addOnunit',
        ),
        migrations.AddField(
            model_name='extralabitem',
            name='lineItemIdNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prosthetic',
            name='extraPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceorder',
            name='lineOrderPrice',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='extralabitem',
            name='lineItemId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dent.prosthetic'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 22, 4, 624912)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 22, 4, 741575)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 5, 20, 22, 4, 741575)),
        ),
    ]
