# Generated by Django 4.0.4 on 2022-12-20 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0251_imageanalysis_sub_category_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosthetic',
            name='fabrication',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 19, 50, 56, 217298)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 19, 50, 56, 309902)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 19, 50, 56, 310440)),
        ),
    ]
