# Generated by Django 4.0.4 on 2022-12-20 15:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0252_prosthetic_fabrication_alter_organisation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 18, 30, 438527)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 18, 30, 584897)),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='preferredData',
            field=models.CharField(default='digitalData', max_length=100),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 20, 21, 18, 30, 586939)),
        ),
    ]
