# Generated by Django 4.0.4 on 2022-12-21 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dent', '0255_prosthetic_paymentstatus_serviceorder_referto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prosthetic',
            name='paymentStatus',
        ),
        migrations.AlterField(
            model_name='organisation',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 17, 48, 17587)),
        ),
        migrations.AlterField(
            model_name='pack',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 17, 48, 66584)),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='rdate',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 21, 22, 17, 48, 66584)),
        ),
    ]
